// Code generated by go-swagger; DO NOT EDIT.

// Package restapi flexlb
//
//  Flexible load balancer API to control keepalived and haproxy
//
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /flexlb/v1
//  Version: v1
//  Contact: Yaohui Wang<yaohuiwang@outlook.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
